# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='useauth',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='password',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='username',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
