# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='userID',
            new_name='user',
        ),
    ]
