# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20161030_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
