# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20161027_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagories',
            new_name='categories',
        ),
    ]
