# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20161109_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
