# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20161121_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='https://cmput404t02.herokuapp.com/service/', max_length=500, null=True),
        ),
    ]
